### ISSUE TITLE
Create a Docker container for development

### ISSUE THREAD

**Issue by monooso** [Previz-app/io_scene_dnb_previz#15]
Create a Docker container provisioned with Blender, the appropriate version of Python, and any other required development tools.

This is unlikely to be simple. For a start, we have the whole rigmarole of getting macOS sharing an X11 server with the container (which may already be more hassle than it's worth). Then we need to sort out hardware acceleration on the container, which is possible, but another hurdle.

**Comment by charlesfleche** [comment]
The python tests run headless, so maybe a full blown hardware acceleration
is not necessary. And for actually testing the plug-in live (Linux +
macOS), a combination of python virtualenv + linking the plug-in to the
install folder (user local add-on folder) works well.
